import { expect }  from "chai";
import { ethers }  from "hardhat";
import { time }    from "@nomicfoundation/hardhat-toolbox/network-helpers";
// TypeChain types are generated by `hardhat compile` — safe to use `as any` during dev
/* eslint-disable @typescript-eslint/no-explicit-any */

describe("Child First Platform — Full Test Suite", function () {

  // ─── Shared state ────────────────────────────────────────────────────
  let factory:  any;
  let receipt:  any;
  let campaign: any;

  let owner:    any;
  let operator: any;
  let director: any;
  let donor1:   any;
  let donor2:   any;
  let stranger: any;

  const CAMPAIGN_ID  = "camp-001-food-atlanta";
  const METADATA_URI = "https://api.childfirst.org/campaigns/001";
  const GOAL         = ethers.parseEther("10");

  let deadline: number;

  // ─── Re-deploy before every test ─────────────────────────────────────
  beforeEach(async function () {
    [owner, operator, director, donor1, donor2, stranger] = await ethers.getSigners();
    deadline = (await time.latest()) + 30 * 24 * 60 * 60; // 30 days

    const Factory = await ethers.getContractFactory("CampaignFactory");
    factory = await Factory.deploy(owner.address) as CampaignFactory;
    await factory.waitForDeployment();

    const receiptAddr = await factory.receiptContract();
    receipt = await ethers.getContractAt("DonationReceipt", receiptAddr) as DonationReceipt;

    // Create the first campaign
    const tx = await factory.createCampaign(
      CAMPAIGN_ID,
      METADATA_URI,
      GOAL,
      deadline,
      operator.address,
      director.address,
    );
    const rec = await tx.wait();

    // Find the CampaignCreated log using TypeChain-aware parsing
    let campaignAddress = "";
    for (const log of rec!.logs) {
      try {
        const parsed = factory.interface.parseLog(log as never);
        if (parsed && parsed.name === "CampaignCreated") {
          campaignAddress = parsed.args.campaignAddress;
          break;
        }
      } catch { /* skip logs from other contracts */ }
    }

    campaign = await ethers.getContractAt("Campaign", campaignAddress);
  });

  // ═══════════════════════════════════════════════════════════════════════
  // CampaignFactory
  // ═══════════════════════════════════════════════════════════════════════
  describe("CampaignFactory", function () {

    it("deploys with correct owner", async function () {
      expect(await factory.owner()).to.equal(owner.address);
    });

    it("deploys a DonationReceipt NFT contract", async function () {
      expect(await factory.receiptContract()).to.not.equal(ethers.ZeroAddress);
    });

    it("registers the campaign in storage", async function () {
      expect(await factory.getCampaignCount()).to.equal(1);
      const addr = await factory.campaignById(CAMPAIGN_ID);
      expect(addr).to.equal(await campaign.getAddress());
      expect(await factory.isCampaign(addr)).to.be.true;
    });

    it("rejects duplicate campaign IDs", async function () {
      await expect(
        factory.createCampaign(CAMPAIGN_ID, "", GOAL, deadline, operator.address, director.address),
      ).to.be.revertedWith("Factory: campaign ID exists");
    });

    it("rejects campaigns with deadline in the past", async function () {
      await expect(
        factory.createCampaign("camp-stale", "", GOAL, (await time.latest()) - 1, operator.address, director.address),
      ).to.be.revertedWith("Factory: deadline in past");
    });

    it("rejects campaigns with zero goal", async function () {
      await expect(
        factory.createCampaign("camp-zero", "", 0, deadline, operator.address, director.address),
      ).to.be.revertedWith("Factory: zero goal");
    });

    it("only owner can create campaigns", async function () {
      await expect(
        factory.connect(donor1).createCampaign("camp-x", "", GOAL, deadline, operator.address, director.address),
      ).to.be.revertedWithCustomError(factory, "OwnableUnauthorizedAccount");
    });

    it("grants new campaign MINTER_ROLE on receipt contract", async function () {
      const MINTER_ROLE = await receipt.MINTER_ROLE();
      expect(await receipt.hasRole(MINTER_ROLE, await campaign.getAddress())).to.be.true;
    });

    it("returns all campaign summaries", async function () {
      const summaries = await factory.getCampaignSummaries();
      expect(summaries.ids[0]).to.equal(CAMPAIGN_ID);
      expect(summaries.goals[0]).to.equal(GOAL);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // Campaign — Donations
  // ═══════════════════════════════════════════════════════════════════════
  describe("Campaign — Donations", function () {

    it("accepts a donation and mints an NFT receipt", async function () {
      const amount = ethers.parseEther("1");

      await expect(campaign.connect(donor1).donate({ value: amount }))
        .to.emit(campaign, "DonationReceived")
        .withArgs(donor1.address, amount, 0n);

      expect(await campaign.totalRaised()).to.equal(amount);
      expect(await campaign.donorTotals(donor1.address)).to.equal(amount);
      expect(await receipt.balanceOf(donor1.address)).to.equal(1n);
    });

    it("mints a distinct NFT per donation", async function () {
      await campaign.connect(donor1).donate({ value: ethers.parseEther("1") });
      await campaign.connect(donor1).donate({ value: ethers.parseEther("2") });

      expect(await receipt.balanceOf(donor1.address)).to.equal(2n);
      expect(await campaign.donorTotals(donor1.address)).to.equal(ethers.parseEther("3"));
    });

    it("multiple donors each receive NFTs", async function () {
      await campaign.connect(donor1).donate({ value: ethers.parseEther("1") });
      await campaign.connect(donor2).donate({ value: ethers.parseEther("2") });

      expect(await receipt.balanceOf(donor1.address)).to.equal(1n);
      expect(await receipt.balanceOf(donor2.address)).to.equal(1n);
      expect(await campaign.totalRaised()).to.equal(ethers.parseEther("3"));
    });

    it("rejects zero-value donations", async function () {
      await expect(campaign.connect(donor1).donate({ value: 0 }))
        .to.be.revertedWith("Campaign: zero donation");
    });

    it("rejects donations after the deadline", async function () {
      await time.increase(31 * 24 * 60 * 60);
      await expect(campaign.connect(donor1).donate({ value: ethers.parseEther("1") }))
        .to.be.revertedWith("Campaign: deadline passed");
    });

    it("blocks direct ETH transfers (must use donate())", async function () {
      await expect(
        donor1.sendTransaction({ to: await campaign.getAddress(), value: ethers.parseEther("1") }),
      ).to.be.revertedWith("Campaign: use donate()");
    });

    it("pauses and unpauses correctly (director can pause)", async function () {
      await campaign.connect(director).pause();
      await expect(campaign.connect(donor1).donate({ value: ethers.parseEther("1") }))
        .to.be.revertedWithCustomError(campaign, "EnforcedPause");

      await campaign.connect(owner).unpause();
      await expect(campaign.connect(donor1).donate({ value: ethers.parseEther("1") }))
        .not.to.be.reverted;
    });

    it("stranger cannot pause", async function () {
      await expect(campaign.connect(stranger).pause())
        .to.be.revertedWith("Campaign: not authorized to pause");
    });

    it("closes campaign and rejects subsequent donations", async function () {
      await campaign.connect(owner).closeCampaign();
      await expect(campaign.connect(donor1).donate({ value: ethers.parseEther("1") }))
        .to.be.revertedWith("Campaign: closed");
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // Campaign — Milestones and Disbursement
  // ═══════════════════════════════════════════════════════════════════════
  describe("Campaign — Milestones & Disbursement", function () {

    beforeEach(async function () {
      // Fund the campaign with 5 MATIC before each milestone test
      await campaign.connect(donor1).donate({ value: ethers.parseEther("5") });
    });

    it("operator can add a milestone", async function () {
      await expect(
        campaign.connect(operator).addMilestone(
          "Purchase food for 50 children",
          ethers.parseEther("2"),
          director.address,
        ),
      ).to.emit(campaign, "MilestoneAdded");

      expect(await campaign.getMilestoneCount()).to.equal(1n);
    });

    it("non-operator cannot add milestone", async function () {
      await expect(
        campaign.connect(donor1).addMilestone(
          "Hack attempt",
          ethers.parseEther("1"),
          donor1.address,
        ),
      ).to.be.revertedWithCustomError(campaign, "AccessControlUnauthorizedAccount");
    });

    it("rejects milestone targeting more than available funds", async function () {
      await expect(
        campaign.connect(operator).addMilestone(
          "Overspend",
          ethers.parseEther("10"), // only 5 available
          director.address,
        ),
      ).to.be.revertedWith("Campaign: target exceeds available funds");
    });

    it("full dual-approval flow disburses correctly", async function () {
      const recipient = director.address;
      const amount    = ethers.parseEther("2");

      await campaign.connect(operator).addMilestone("Food supplies", amount, recipient);
      await campaign.connect(operator).operatorApproveMilestone(0);

      // Only operator approved — should not disburse
      await expect(campaign.disburseMilestone(0))
        .to.be.revertedWith("Campaign: director approval pending");

      await campaign.connect(director).directorApproveMilestone(0);

      const before = await ethers.provider.getBalance(recipient);
      await expect(campaign.disburseMilestone(0))
        .to.emit(campaign, "MilestoneDisbursed")
        .withArgs(0n, recipient, amount);
      const after = await ethers.provider.getBalance(recipient);

      expect(after - before).to.equal(amount);
      const m = await campaign.getMilestone(0);
      expect(m.disbursed).to.be.true;
    });

    it("cannot disburse the same milestone twice", async function () {
      await campaign.connect(operator).addMilestone("Food", ethers.parseEther("1"), director.address);
      await campaign.connect(operator).operatorApproveMilestone(0);
      await campaign.connect(director).directorApproveMilestone(0);
      await campaign.disburseMilestone(0);

      await expect(campaign.disburseMilestone(0))
        .to.be.revertedWith("Campaign: already disbursed");
    });

    it("director cannot add milestones", async function () {
      await expect(
        campaign.connect(director).addMilestone("Test", ethers.parseEther("1"), director.address),
      ).to.be.revertedWithCustomError(campaign, "AccessControlUnauthorizedAccount");
    });

    it("non-director cannot approve milestone as director", async function () {
      await campaign.connect(operator).addMilestone("Test", ethers.parseEther("1"), director.address);
      await expect(campaign.connect(operator).directorApproveMilestone(0))
        .to.be.revertedWithCustomError(campaign, "AccessControlUnauthorizedAccount");
    });

    it("availableFunds decrements correctly", async function () {
      const balance = await ethers.provider.getBalance(await campaign.getAddress());
      await campaign.connect(operator).addMilestone("Test", ethers.parseEther("2"), director.address);
      const available = await campaign.availableFunds();
      expect(available).to.equal(balance - ethers.parseEther("2"));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════
  // DonationReceipt NFT
  // ═══════════════════════════════════════════════════════════════════════
  describe("DonationReceipt NFT", function () {

    it("token is soulbound — cannot be transferred", async function () {
      await campaign.connect(donor1).donate({ value: ethers.parseEther("1") });

      await expect(
        receipt.connect(donor1).transferFrom(donor1.address, donor2.address, 0),
      ).to.be.revertedWith("DonationReceipt: non-transferable");
    });

    it("generates valid on-chain base64 JSON token URI", async function () {
      await campaign.connect(donor1).donate({ value: ethers.parseEther("1.5") });

      const uri = await receipt.tokenURI(0);
      expect(uri).to.include("data:application/json;base64,");

      const json = JSON.parse(
        Buffer.from(uri.replace("data:application/json;base64,", ""), "base64").toString("utf8"),
      );
      expect(json.name).to.equal("Donation Receipt #0");
      expect(json.description).to.include("Child First Platform");
      expect(json.image).to.include("data:image/svg+xml;base64,");
      expect(json.attributes).to.have.length(3);
    });

    it("stores receipt data with correct values", async function () {
      const amount = ethers.parseEther("2");
      await campaign.connect(donor1).donate({ value: amount });

      const data = await receipt.getReceiptData(0);
      expect(data.campaignId).to.equal(CAMPAIGN_ID);
      expect(data.amount).to.equal(amount);
      expect(data.donor).to.equal(donor1.address);
    });

    it("only registered Campaign contracts can mint receipts", async function () {
      await expect(
        receipt.connect(stranger).mintReceipt(
          stranger.address,
          "fake-campaign",
          ethers.parseEther("1"),
          Math.floor(Date.now() / 1000),
        ),
      ).to.be.revertedWithCustomError(receipt, "AccessControlUnauthorizedAccount");
    });

    it("reverts tokenURI for non-existent token", async function () {
      await expect(receipt.tokenURI(999))
        .to.be.revertedWithCustomError(receipt, "ERC721NonexistentToken");
    });
  });
});
